" For Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" Just set pythonthreedll is enough, if set pythonthreehome, will see python
" error: ModuleNotFoundError: No module named 'encodings' when vim starting
set pythonthreedll=/c/Users/02569/AppData/Local/Programs/Python/Python36-32/python36.dll

" set the runtime path to include Vundle and initialize
" I copy the installed vim plugins from C:\[vim install]\vimfiles to ~/.vim/bundle folder, so can set rtp
" to ~/.vim/bundle/Vundle.vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle/')
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'Valloric/YouCompleteMe'

" Add the html5 tag to vim omnicomplete tag list
Plugin 'othree/html5.vim'

" html tag auto close
Plugin 'alvan/vim-closetag'

" auto close brackets
Plugin 'jiangmiao/auto-pairs'

" nerdtree
Plugin 'preservim/nerdtree'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" For YouCompleteMe
let g:ycm_global_ycm_extra_conf = 'C:\Users\02569\.vim\bundle\YouCompleteMe\third_party\ycmd\.ycm_extra_conf.py'
" Hot key map
" Jump definition
nnoremap <leader>jd :YcmCompleter GoTo<CR>

" automatically close preview window after leaving insert mode
let g:ycm_autoclose_preview_window_after_completion = 1

" YCM auto complete for specific languages
let g:ycm_semantic_triggers = {
   \   'scss,sass,css': [ 're!^\s{4}', 're!:\s+' ],
   \   'html': ['<', '"', '</', ' '],
   \ }


set shiftwidth=4
set tabstop=4
set expandtab
color torte
set smartindent
set guifont=Consolas:h11
set hls
set nobackup
set nu
set noequalalways
set noundofile
set encoding=utf-8
set tw=0
autocmd FileType javascript setlocal tabstop=2 shiftwidth=2 expandtab
autocmd FileType html setlocal tabstop=2 shiftwidth=2 expandtab
autocmd BufNewFile,BufRead *.ejs set filetype=html
" The YCM quit handler is registered to VimLeave, but for unknown reason the git for windows 
" builtin vim does not call VimLeave when using :q to quit vim.
" After testing the QuitPre event works, so manually register YCM quit handler to QuitPre
autocmd QuitPre * py3 ycm_state.OnVimLeave()

autocmd VimEnter * NERDTree
autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

nnoremap <silent> <F5> :NERDTree<CR>

" Let gvim can read utf8 and big5
" set enc=utf-8
" set fileencodings=utf-8,gbk,cp950,latin1
set nobomb

" Change the working directory at the same time when you change the root of nerd tree
let NERDTreeChDirMode=2
