" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

" For status line
function! InsertStatuslineColor(mode)
  if a:mode == 'i'
    hi statusline guibg=magenta
  elseif a:mode == 'r'
    hi statusline guibg=blue
  else
    hi statusline guibg=red
  endif
endfunction

au InsertEnter * call InsertStatuslineColor(v:insertmode)
au InsertChange * call InsertStatuslineColor(v:insertmode)
au InsertLeave * hi statusline guibg=green

" default the statusline to green when entering Vim
hi statusline guibg=green
set laststatus=2

" For Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=$VIM/vimfiles/bundle/Vundle.vim
call vundle#begin('$VIM/vimfiles/bundle/')
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'Valloric/YouCompleteMe'

" Add the html5 tag to vim omnicomplete tag list
Plugin 'othree/html5.vim'

" html tag auto close
Plugin 'alvan/vim-closetag'

" auto close brackets
Plugin 'jiangmiao/auto-pairs'

" nerdtree
Plugin 'preservim/nerdtree'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" For YouCompleteMe
let g:ycm_global_ycm_extra_conf = 'C:\Program Files (x86)\Vim\vimfiles\bundle\YouCompleteMe\third_party\ycmd\.ycm_extra_conf.py'
" Hot key map
" Jump definition
nnoremap <leader>jd :YcmCompleter GoTo<CR>

" automatically close preview window after leaving insert mode
let g:ycm_autoclose_preview_window_after_completion = 1

" YCM auto complete for specific languages
let g:ycm_semantic_triggers = {
   \   'scss,sass,css': [ 're!^\s{4}', 're!:\s+' ],
   \   'html': ['<', '"', '</', ' '],
   \ }


set shiftwidth=4
set tabstop=4
set expandtab
color torte
set smartindent
set guifont=Consolas:h11
set hls
set nobackup
set nu
set noequalalways
set noundofile
set encoding=utf-8
set pythonthreedll=C:\Users\02569\AppData\Local\Programs\Python\Python36-32\python36.dll
set tw=0
set cursorline
hi clear cursorline
hi CursorLine gui=underline cterm=underline
autocmd FileType javascript setlocal tabstop=2 shiftwidth=2 expandtab
autocmd FileType html setlocal tabstop=2 shiftwidth=2 expandtab
autocmd BufNewFile,BufRead *.ejs set filetype=html
" autocmd QuitPre * py3 ycm_state.OnVimLeave()
autocmd VimLeave * call writefile([v:dying], 'D:\\vimtest')

" stop vim set tw=78 for txt files
au! vimrcEx FileType text

if has("gui_running")
    set guioptions-=m
    set guioptions-=T
endif


autocmd vimenter * NERDTree
autocmd bufenter * nested if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

nnoremap <silent> <F5> :NERDTree<CR>

" Let gvim can read utf8 and big5
set enc=utf-8
set fileencodings=utf-8,gbk,cp950,latin1
set nobomb

" Reload menu with UTF-8 encoding to avoid garbled menu
let $LANG="zh_TW.UTF-8"
set langmenu=zh_tw.utf-8
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

" Change the working directory at the same time when you change the root of nerd tree
let NERDTreeChDirMode=2
